# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rcmdsys.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rcmdsys.proto',
  package='rcmdsys',
  syntax='proto3',
  serialized_options=b'Z\010/rcmdsys',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrcmdsys.proto\x12\x07rcmdsys\"7\n\x06Record\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06probId\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x03UId\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tmaxLength\x18\x02 \x01(\x05\"\x15\n\x07ProbAry\x12\n\n\x02id\x18\x01 \x03(\t2_\n\x07Rcmdsys\x12)\n\x03Upd\x12\x0f.rcmdsys.Record\x1a\x0f.rcmdsys.Status\"\x00\x12)\n\x05Query\x12\x0c.rcmdsys.UId\x1a\x10.rcmdsys.ProbAry\"\x00\x42\nZ\x08/rcmdsysb\x06proto3'
)




_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='rcmdsys.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='rcmdsys.Record.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probId', full_name='rcmdsys.Record.probId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='rcmdsys.Record.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=81,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='rcmdsys.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rcmdsys.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=107,
)


_UID = _descriptor.Descriptor(
  name='UId',
  full_name='rcmdsys.UId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rcmdsys.UId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxLength', full_name='rcmdsys.UId.maxLength', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=145,
)


_PROBARY = _descriptor.Descriptor(
  name='ProbAry',
  full_name='rcmdsys.ProbAry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rcmdsys.ProbAry.id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['UId'] = _UID
DESCRIPTOR.message_types_by_name['ProbAry'] = _PROBARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), {
  'DESCRIPTOR' : _RECORD,
  '__module__' : 'rcmdsys_pb2'
  # @@protoc_insertion_point(class_scope:rcmdsys.Record)
  })
_sym_db.RegisterMessage(Record)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'rcmdsys_pb2'
  # @@protoc_insertion_point(class_scope:rcmdsys.Status)
  })
_sym_db.RegisterMessage(Status)

UId = _reflection.GeneratedProtocolMessageType('UId', (_message.Message,), {
  'DESCRIPTOR' : _UID,
  '__module__' : 'rcmdsys_pb2'
  # @@protoc_insertion_point(class_scope:rcmdsys.UId)
  })
_sym_db.RegisterMessage(UId)

ProbAry = _reflection.GeneratedProtocolMessageType('ProbAry', (_message.Message,), {
  'DESCRIPTOR' : _PROBARY,
  '__module__' : 'rcmdsys_pb2'
  # @@protoc_insertion_point(class_scope:rcmdsys.ProbAry)
  })
_sym_db.RegisterMessage(ProbAry)


DESCRIPTOR._options = None

_RCMDSYS = _descriptor.ServiceDescriptor(
  name='Rcmdsys',
  full_name='rcmdsys.Rcmdsys',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upd',
    full_name='rcmdsys.Rcmdsys.Upd',
    index=0,
    containing_service=None,
    input_type=_RECORD,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='rcmdsys.Rcmdsys.Query',
    index=1,
    containing_service=None,
    input_type=_UID,
    output_type=_PROBARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RCMDSYS)

DESCRIPTOR.services_by_name['Rcmdsys'] = _RCMDSYS

# @@protoc_insertion_point(module_scope)
