# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rcmdsys_pb2 as rcmdsys__pb2


class RcmdsysStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upd = channel.unary_unary(
                '/rcmdsys.Rcmdsys/Upd',
                request_serializer=rcmdsys__pb2.Record.SerializeToString,
                response_deserializer=rcmdsys__pb2.Status.FromString,
                )
        self.Query = channel.unary_unary(
                '/rcmdsys.Rcmdsys/Query',
                request_serializer=rcmdsys__pb2.UId.SerializeToString,
                response_deserializer=rcmdsys__pb2.ProbAry.FromString,
                )


class RcmdsysServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RcmdsysServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upd': grpc.unary_unary_rpc_method_handler(
                    servicer.Upd,
                    request_deserializer=rcmdsys__pb2.Record.FromString,
                    response_serializer=rcmdsys__pb2.Status.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=rcmdsys__pb2.UId.FromString,
                    response_serializer=rcmdsys__pb2.ProbAry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rcmdsys.Rcmdsys', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Rcmdsys(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcmdsys.Rcmdsys/Upd',
            rcmdsys__pb2.Record.SerializeToString,
            rcmdsys__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcmdsys.Rcmdsys/Query',
            rcmdsys__pb2.UId.SerializeToString,
            rcmdsys__pb2.ProbAry.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
