// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        v3.11.4
// source: rcmdsys.proto

package rcmdsys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProbId string  `protobuf:"bytes,2,opt,name=probId,proto3" json:"probId,omitempty"`
	Score  float64 `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcmdsys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_rcmdsys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_rcmdsys_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Record) GetProbId() string {
	if x != nil {
		return x.ProbId
	}
	return ""
}

func (x *Record) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcmdsys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_rcmdsys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_rcmdsys_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaxLength int32  `protobuf:"varint,2,opt,name=maxLength,proto3" json:"maxLength,omitempty"`
}

func (x *UId) Reset() {
	*x = UId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcmdsys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UId) ProtoMessage() {}

func (x *UId) ProtoReflect() protoreflect.Message {
	mi := &file_rcmdsys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UId.ProtoReflect.Descriptor instead.
func (*UId) Descriptor() ([]byte, []int) {
	return file_rcmdsys_proto_rawDescGZIP(), []int{2}
}

func (x *UId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UId) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

type ProbAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *ProbAry) Reset() {
	*x = ProbAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcmdsys_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbAry) ProtoMessage() {}

func (x *ProbAry) ProtoReflect() protoreflect.Message {
	mi := &file_rcmdsys_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbAry.ProtoReflect.Descriptor instead.
func (*ProbAry) Descriptor() ([]byte, []int) {
	return file_rcmdsys_proto_rawDescGZIP(), []int{3}
}

func (x *ProbAry) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_rcmdsys_proto protoreflect.FileDescriptor

var file_rcmdsys_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x63, 0x6d, 0x64, 0x73, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x63, 0x6d, 0x64, 0x73, 0x79, 0x73, 0x22, 0x4e, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72,
	0x6f, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x62,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x33, 0x0a, 0x03, 0x55, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22,
	0x19, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x62, 0x41, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x5f, 0x0a, 0x07, 0x52, 0x63,
	0x6d, 0x64, 0x73, 0x79, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x55, 0x70, 0x64, 0x12, 0x0f, 0x2e, 0x72,
	0x63, 0x6d, 0x64, 0x73, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x0f, 0x2e,
	0x72, 0x63, 0x6d, 0x64, 0x73, 0x79, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x12, 0x29, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0c, 0x2e, 0x72, 0x63, 0x6d, 0x64,
	0x73, 0x79, 0x73, 0x2e, 0x55, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x72, 0x63, 0x6d, 0x64, 0x73, 0x79,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x41, 0x72, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f,
	0x72, 0x63, 0x6d, 0x64, 0x73, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rcmdsys_proto_rawDescOnce sync.Once
	file_rcmdsys_proto_rawDescData = file_rcmdsys_proto_rawDesc
)

func file_rcmdsys_proto_rawDescGZIP() []byte {
	file_rcmdsys_proto_rawDescOnce.Do(func() {
		file_rcmdsys_proto_rawDescData = protoimpl.X.CompressGZIP(file_rcmdsys_proto_rawDescData)
	})
	return file_rcmdsys_proto_rawDescData
}

var file_rcmdsys_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rcmdsys_proto_goTypes = []interface{}{
	(*Record)(nil),  // 0: rcmdsys.Record
	(*Status)(nil),  // 1: rcmdsys.Status
	(*UId)(nil),     // 2: rcmdsys.UId
	(*ProbAry)(nil), // 3: rcmdsys.ProbAry
}
var file_rcmdsys_proto_depIdxs = []int32{
	0, // 0: rcmdsys.Rcmdsys.Upd:input_type -> rcmdsys.Record
	2, // 1: rcmdsys.Rcmdsys.Query:input_type -> rcmdsys.UId
	1, // 2: rcmdsys.Rcmdsys.Upd:output_type -> rcmdsys.Status
	3, // 3: rcmdsys.Rcmdsys.Query:output_type -> rcmdsys.ProbAry
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rcmdsys_proto_init() }
func file_rcmdsys_proto_init() {
	if File_rcmdsys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rcmdsys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcmdsys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcmdsys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcmdsys_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rcmdsys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rcmdsys_proto_goTypes,
		DependencyIndexes: file_rcmdsys_proto_depIdxs,
		MessageInfos:      file_rcmdsys_proto_msgTypes,
	}.Build()
	File_rcmdsys_proto = out.File
	file_rcmdsys_proto_rawDesc = nil
	file_rcmdsys_proto_goTypes = nil
	file_rcmdsys_proto_depIdxs = nil
}
